# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_ctmcSim_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_ctmcSim_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_ctmcSim_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_ctmcSim_rcpparma_bothproducts`, x)
}

get_beta <- function(Nbasis, a, b, c) {
    .Call(`_ctmcSim_get_beta`, Nbasis, a, b, c)
}

simTWO <- function(a = 1., b = 0., c = 2.0) {
    .Call(`_ctmcSim_simTWO`, a, b, c)
}

